# Generated by Django 6.0.3 on 2026-03-21 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='destaque_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='noticia',
            name='resumo',
            field=models.CharField(default='Noticia', max_length=250),
            preserve_default=False,
        ),
    ]
